version: '3.5'

services:
  importer:
    build:
      context: .
    volumes:
      - './data/:/data'
    env_file:
      - ./docker.env
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata/:/data/db

volumes:
  mongodbdata:
    driver: local
