version: '3.5'

services:
  importer:
    build:
      context: .
    volumes:
      - './data/:/data'
    environment:
      - MONGODB=mongodb://mongodb:27017/
      - BASEPATH_DATA=/data
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_DATABASE: importer
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata/:/data/db

volumes:
  mongodbdata:
    driver: local
